[package]
name = "powers"
version = "2.3.0"
authors = ["Ruby <ruby@rubidium.dev>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
chrono = "0.4.19"
md5 = "0.7.0"
num_enum = "0.5.1"
serde = { version = "1.0.117", features = ["rc", "serde_derive"] }
serde_json = "1.0.59"
toml = "0.5.7"
